name: Update Leaderboard

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    defaults:
      run:
        working-directory: leaderboard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate the leaderboard
      run: |
        python script.py participants.csv

    - name: Commit the leaderboard
      run: |
        if [[ `git status --porcelain` ]]; then
          git add -A
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Update Leaderboard: $(date '+%Y-%m-%d')"
          git push
        else
          echo "No changes detected"
        fi
